name = "my-negotiator-app"
main = "src/index.ts"
compatibility_date = "2024-12-22"

"d1_databases": [{
    "binding": "DB",
    "database_name": "negotiator-db",
    "database_id": "40fb3ddd-bbed-4c95-8139-66d26bb5d49c"
 }]
