name = "my-negotiator-app"
main = "src/index.ts"
compatibility_date = "2024-12-22"

# ... (上の内容は消さずに、一番下に追記)

[[d1_databases]]
binding = "DB"
database_name = "my-negotiator-db"
database_id = "40fb3ddd-bbed-4c95-8139-66d26bb5d49c"


[vars]
# Stripeダッシュボードで作成したPrice ID (price_...) を設定してください
STRIPE_PRICE_ID_YEARLY = "price_1Ro1SWIrUlY19KORHTEZi07o"  # 年額プラン
STRIPE_PRICE_ID_MONTHLY = "price_1SjDPdIrpTPay9KgjUkWu3yA" # 月額プラン
FRONTEND_URL = "https://my-negotiator-app.pages.dev"
